init(i1)
action(n1, "start procedure")
action(n2, "assess potential for seizure")
action(n3, "assess potential for significant hemorrhage")
action(n4, "assess potential for acute respiratory distress")
action(n5, "all assessments complete")
action(n6, "is midazolam needed")
branch(b1, XOR)
action(n7, "administer midazolam 10 mg")
action(n8, "procedure complete")
end(e1)
action(n9, "procedure complete")
end(e2)
converge(c1)
branch(b2, AND)
defines(v1, "is midazolam needed", {"Yes", "No"})
actor(a_default, "Default", [i1, n1, n2, n3, n4, n5, n6, b1, n7, n8, e1, n9, e2, c1, b2])
precedence(i1, n1)
precedence(n6, b1)
precedence(n8, e1)
precedence(n9, e2)
precedence(c1, n5)
precedence(n1, b2)
precedence(b2, n2)
precedence(b2, n3)
precedence(b2, n4)
precedence(n2, c1)
precedence(n3, c1)
precedence(n4, c1)
precedence(n5, n6)
precedence(b1, n7)
precedence(n7, n8)
precedence(b1, n9)
guard(b1, n7, v1 = 'Yes')
guard(b1, n9, v1 = 'No')
