init(i1)
action(n1, "start ExpenseReport process by clicking Start then selecting Edit Report")
action(n2, "Is expense greater than 1000")
branch(b1, XOR)
action(n3, "review the report")
action(n4, "Is translation needed")
branch(b2, XOR)
action(n5, "translate the receipts")
action(n6, "confirm the receipts")
action(n7, "evaluate review decision")
branch(b3, XOR)
action(n8, "Is report rejected after review")
branch(b4, XOR)
action(n9, "edit the report")
action(n10, "Is report approved after review")
branch(b5, XOR)
action(n11, "check if translation is needed")
branch(b6, XOR)
action(n12, "Is report rejected after second review")
branch(b7, XOR)
action(n13, "edit the report")
action(n14, "Is report approved after second review")
branch(b8, XOR)
action(n15, "translate the receipts")
action(n16, "confirm receipts")
action(n17, "evaluate receipts decision")
branch(b9, XOR)
action(n18, "Are receipts accepted")
branch(b10, XOR)
action(n19, "process the expense")
action(n20, "edit the report")
action(n21, "end process")
end(e1)
converge(c1)
defines(v1, "Is expense greater than 1000", {})
defines(v2, "Is translation needed", {})
defines(v3, "evaluate review decision", {})
defines(v4, "Is report rejected after review", {})
defines(v5, "Is report approved after review", {})
defines(v6, "check if translation is needed", {})
defines(v7, "Is report rejected after second review", {})
defines(v8, "Is report approved after second review", {})
defines(v9, "evaluate receipts decision", {})
defines(v10, "Are receipts accepted", {})
actor(a_default, "Default", [i1, n1, n2, b1, n3, n4, b2, n5, n6, n7, b3, n8, b4, n9, n10, b5, n11, b6, n12, b7, n13, n14, b8, n15, n16, n17, b9, n18, b10, n19, n20, n21, e1, c1])
precedence(i1, n1)
precedence(n2, b1)
precedence(n4, b2)
precedence(n7, b3)
precedence(n8, b4)
precedence(n10, b5)
precedence(n11, b6)
precedence(n12, b7)
precedence(n14, b8)
precedence(n17, b9)
precedence(n18, b10)
precedence(n21, e1)
precedence(c1, n7)
precedence(n1, n2)
precedence(b1, n3)
precedence(b1, n4)
precedence(b2, n5)
precedence(b2, n6)
precedence(n3, c1)
precedence(n5, c1)
precedence(n6, c1)
precedence(b3, n8)
precedence(b4, n9)
precedence(b3, n10)
precedence(b5, n11)
precedence(b6, n12)
precedence(b7, n13)
precedence(b6, n14)
precedence(b8, n15)
precedence(n15, n16)
precedence(n16, n17)
precedence(b9, n18)
precedence(b10, n19)
precedence(b10, n20)
precedence(n19, n21)
