init(i1)
action(n1, "start")
action(n2, "select a filter")
action(n3, "apply the selected filter")
action(n4, "click on Submit button")
action(n5, "is option to submit false")
branch(b1, XOR)
action(n6, "apply another filter")
action(n7, "click on Submit button again")
action(n8, "continue with process after submit false")
action(n9, "is there another filter to apply")
branch(b2, XOR)
action(n10, "continue with process if another filter to apply")
action(n11, "continue with process if no more filters")
action(n12, "is option to submit true")
branch(b3, XOR)
action(n13, "continue with process if option submit true")
action(n14, "end process")
end(e1)
converge(c1)
converge(c2)
defines(v1, "is option to submit false", {})
defines(v2, "is there another filter to apply", {})
defines(v3, "is option to submit true", {"No"})
actor(a_default, "Default", [i1, n1, n2, n3, n4, n5, b1, n6, n7, n8, n9, b2, n10, n11, n12, b3, n13, n14, e1, c1, c2])
precedence(i1, n1)
precedence(n5, b1)
precedence(n9, b2)
precedence(n12, b3)
precedence(n14, e1)
precedence(c1, n9)
precedence(c2, n12)
precedence(n1, n2)
precedence(n2, n3)
precedence(n3, n4)
precedence(n4, n5)
precedence(b1, n6)
precedence(n6, n7)
precedence(b1, n8)
precedence(n7, c1)
precedence(n8, c1)
precedence(b2, n10)
precedence(b2, n11)
precedence(n10, c2)
precedence(n11, c2)
precedence(b3, n13)
precedence(b3, n14)
guard(b3, n14, v3 = 'No')
