init(i1)
action(n1, "start")
action(n2, "provide userdata for flickr")
action(n3, "is login successful")
branch(b1, XOR)
action(n4, "end process")
end(e1)
action(n5, "do you want to try again")
branch(b2, XOR)
action(n6, "provide userdata for flickr")
action(n7, "end process")
end(e2)
action(n8, "do you still want to try again")
branch(b3, XOR)
action(n9, "provide userdata for flickr")
action(n10, "end process")
end(e3)
action(n11, "end process")
end(e4)
defines(v1, "is login successful", {"Yes", "No"})
defines(v2, "do you want to try again", {"Yes", "No"})
defines(v3, "do you still want to try again", {"Yes", "No"})
actor(a_default, "Default", [i1, n1, n2, n3, b1, n4, e1, n5, b2, n6, n7, e2, n8, b3, n9, n10, e3, n11, e4])
precedence(i1, n1)
precedence(n3, b1)
precedence(n4, e1)
precedence(n5, b2)
precedence(n7, e2)
precedence(n8, b3)
precedence(n10, e3)
precedence(n11, e4)
precedence(n1, n2)
precedence(n2, n3)
precedence(b1, n4)
precedence(b1, n5)
precedence(b2, n6)
precedence(b2, n7)
precedence(n6, n8)
precedence(b3, n9)
precedence(b3, n10)
precedence(n9, n11)
guard(b1, n4, v1 = 'Yes')
guard(b1, n5, v1 = 'No')
guard(b2, n6, v2 = 'Yes')
guard(b2, n7, v2 = 'No')
guard(b3, n9, v3 = 'Yes')
guard(b3, n10, v3 = 'No')
